
server.port=8081
webapp.dir=src/main/webapp/
admin.api.token=aboba
rabbit.queue.name=callbackQueue

postgreSQL.datasource.url=jdbc:postgresql://localhost:5432/dictionary_mmtr
postgreSQL.datasource.username=postgres
postgreSQL.datasource.password=root
postgreSQL.datasource.driver-class-name=org.postgresql.Driver

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

